In [16]:
import cv2
import numpy as np

In [25]:

face_classifier = cv2.CascadeClassifier('C:/Users/mahav/Downloads/opencv/sources/data/haarcascades/haarcascade_frontalface_default.xml')


def face_extractor(img):

    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray,1.3,5)

    if faces is():
        return None

    for(x,y,w,h) in faces:
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face


cap = cv2.VideoCapture(0)
count = 0

while True:
    ret, frame = cap.read()
    if face_extractor(frame) is not None:
        count+=1
        Face = cv2.resize(face_extractor(frame),(200,200))
        Face = cv2.cvtColor(Face, cv2.COLOR_BGR2GRAY)

        file_name_path = 'D:/machine learning progrom/face_detection/face/user'+str(count)+'.jpg'
        cv2.imwrite(file_name_path,Face)

        cv2.putText(Face,str(count),(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
        cv2.imshow('Face Cropper',Face)
    else:
        print("Face not Found")
        pass

    if cv2.waitKey(1)==13 or count==100:
        break

cap.release()
cv2.destroyAllWindows()
print('Colleting Samples Complete!!!')

Face not Found
Face not Found
Face not Found
Face not Found
Face not Found
Face not Found
Colleting Samples Complete!!!


In [17]:
import os
from os.path import isfile,join

In [18]:
data='D:/machine learning progrom/face_detection/face/'
only_file=[f for f in os.listdir(data) if isfile(join(data,f))]

In [26]:
traning_data,label=[],[]
for i,file in enumerate(only_file):
    
    image_path=data+only_file[i]
    
    images=cv2.imread(image_path,cv2.IMREAD_GRAYSCALE)
    
    traning_data.append(np.asarray(images,dtype=np.uint8))
    
    label.append(i)
    
label=np.asarray(label,dtype=np.int32)

model =cv2.face.LBPHFaceRecognizer_create()

model.train(np.asarray(traning_data), np.asarray(label))

print("Model Training Complete!!!!!")
    

Model Training Complete!!!!!


In [32]:
only_file

['user1.jpg',
 'user10.jpg',
 'user100.jpg',
 'user11.jpg',
 'user12.jpg',
 'user13.jpg',
 'user14.jpg',
 'user15.jpg',
 'user16.jpg',
 'user17.jpg',
 'user18.jpg',
 'user19.jpg',
 'user2.jpg',
 'user20.jpg',
 'user21.jpg',
 'user22.jpg',
 'user23.jpg',
 'user24.jpg',
 'user25.jpg',
 'user26.jpg',
 'user27.jpg',
 'user28.jpg',
 'user29.jpg',
 'user3.jpg',
 'user30.jpg',
 'user31.jpg',
 'user32.jpg',
 'user33.jpg',
 'user34.jpg',
 'user35.jpg',
 'user36.jpg',
 'user37.jpg',
 'user38.jpg',
 'user39.jpg',
 'user4.jpg',
 'user40.jpg',
 'user41.jpg',
 'user42.jpg',
 'user43.jpg',
 'user44.jpg',
 'user45.jpg',
 'user46.jpg',
 'user47.jpg',
 'user48.jpg',
 'user49.jpg',
 'user5.jpg',
 'user50.jpg',
 'user51.jpg',
 'user52.jpg',
 'user53.jpg',
 'user54.jpg',
 'user55.jpg',
 'user56.jpg',
 'user57.jpg',
 'user58.jpg',
 'user59.jpg',
 'user6.jpg',
 'user60.jpg',
 'user61.jpg',
 'user62.jpg',
 'user63.jpg',
 'user64.jpg',
 'user65.jpg',
 'user66.jpg',
 'user67.jpg',
 'user68.jpg',
 'user69.jpg',


In [35]:
images.shape

(200, 200)

In [36]:
label

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
traning_data

[array([[140, 130, 120, ..., 166, 171, 176],
        [137, 130, 120, ..., 164, 169, 174],
        [134, 127, 116, ..., 162, 167, 171],
        ...,
        [  6,   5,   4, ..., 108, 115, 120],
        [  6,   5,   4, ...,  80,  90,  98],
        [  6,   5,   4, ...,  58,  64,  69]], dtype=uint8),
 array([[144, 111,  59, ..., 180, 183, 184],
        [113,  82,  41, ..., 181, 184, 184],
        [ 77,  51,  25, ..., 181, 183, 184],
        ...,
        [122, 122, 122, ..., 168, 162, 152],
        [119, 120, 120, ..., 167, 165, 154],
        [116, 117, 118, ..., 165, 167, 156]], dtype=uint8),
 array([[182, 182, 182, ...,  61,  99, 133],
        [181, 182, 183, ...,  54,  91, 123],
        [181, 182, 183, ...,  42,  79, 113],
        ...,
        [ 32,  27,  22, ..., 151, 151, 151],
        [ 25,  21,  18, ..., 150, 150, 150],
        [ 21,  19,  16, ..., 149, 149, 149]], dtype=uint8),
 array([[144, 111,  59, ..., 180, 183, 184],
        [113,  82,  41, ..., 181, 184, 184],
        [ 77,  5

In [31]:
import cv2
import numpy as np
from os import listdir
from os.path import isfile, join

data_path = 'D:/machine learning progrom/face_detection/face/'
onlyfiles = [f for f in listdir(data_path) if isfile(join(data_path,f))]

Training_Data, Labels = [], []

for i, files in enumerate(onlyfiles):
    image_path = data_path + onlyfiles[i]
    images = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    Training_Data.append(np.asarray(images, dtype=np.uint8))
    Labels.append(i)

Labels = np.asarray(Labels, dtype=np.int32)

model = cv2.face.LBPHFaceRecognizer_create()

model.train(np.asarray(Training_Data), np.asarray(Labels))

print("Model Training Complete!!!!!")

face_classifier = cv2.CascadeClassifier('C:/Users/mahav/Downloads/opencv/sources/data/haarcascades/haarcascade_frontalface_default.xml')

def face_detector(img, size = 0.5):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray,1.3,5)

    if faces is():
        return img,[]

    for(x,y,w,h) in faces:
        cv2.rectangle(img, (x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi, (200,200))

    return img,roi

cap = cv2.VideoCapture(0)
while True:

    ret, frame = cap.read()

    image, face = face_detector(frame)

    try:
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
        result = model.predict(face)
        print(result)

        if result[1] < 500:
            confidence = int(100*(1-(result[1])/300))
            display_string = str(confidence)+'% Confidence it is user'
        cv2.putText(image,display_string,(100,120), cv2.FONT_HERSHEY_COMPLEX,1,(250,120,255),2)


        if confidence > 75:
            cv2.putText(image, "Unlocked", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
            cv2.imshow('Face Cropper', image)

        else:
            cv2.putText(image, "Locked", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0, 255), 2)
            cv2.imshow('Face Cropper', image)


    except:
        cv2.putText(image, "Face Not Found", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0), 2)
        cv2.imshow('Face Cropper', image)
        pass

    if cv2.waitKey(1)==13:
        break


cap.release()
cv2.destroyAllWindows()

Model Training Complete!!!!!
(26, 38.19092524025392)
(26, 44.11593905036955)
(26, 44.11593905036955)
(26, 41.730022910126564)
(26, 41.730022910126564)
(26, 44.245480619026495)
(26, 44.245480619026495)
(26, 43.23455410917987)
(26, 43.23455410917987)
(26, 42.82141314299695)
(26, 42.82141314299695)
(26, 43.22477237156013)
(26, 43.22477237156013)
(26, 41.19645556590626)
(26, 41.19645556590626)
(69, 48.254576938333294)
(69, 48.254576938333294)
(73, 55.97423511811439)
(73, 55.97423511811439)
(73, 57.361158312847856)
(73, 57.361158312847856)
(73, 50.199453696584285)
(73, 50.199453696584285)
(69, 45.019682738301015)
(69, 45.019682738301015)
(69, 39.027137929526916)
(73, 49.47194359425187)
(73, 49.47194359425187)
(88, 38.60888445037254)
(88, 38.60888445037254)
(69, 45.162985185582535)
(69, 45.162985185582535)
(88, 37.27851735244243)
(88, 37.27851735244243)
(88, 40.98064539548651)
(88, 40.98064539548651)
(88, 38.42978944468919)
(88, 38.42978944468919)
(88, 38.38412920767404)
(88, 38.384129207674

(88, 38.44703700280628)
(88, 35.821714637367805)
(88, 35.821714637367805)
(88, 38.56824426677193)
(88, 39.07376186107117)
(88, 39.07376186107117)
(88, 38.64890987813593)
(88, 38.64890987813593)
(88, 39.9398383501201)
(88, 39.9398383501201)
(88, 45.577659552058826)
(88, 45.577659552058826)
(69, 55.27892255086134)
(69, 55.27892255086134)
(18, 59.48473384842801)
(18, 59.48473384842801)
(88, 54.851641833383994)
(88, 54.851641833383994)
(73, 56.05168910628877)
(73, 56.05168910628877)
(64, 58.1313471642626)
(30, 62.47127227290481)
(30, 62.47127227290481)
(88, 59.502489840221926)
(88, 59.502489840221926)
(97, 57.72568730531507)
(97, 57.72568730531507)
(97, 56.67359935779415)
(97, 56.67359935779415)
(97, 58.83382332886609)
(97, 58.83382332886609)
(88, 57.72102098057957)
(88, 57.72102098057957)
(88, 55.218878998491036)
(88, 55.218878998491036)
(97, 55.70574881312534)
(97, 55.70574881312534)
(73, 57.02674713446263)
(73, 57.02674713446263)
(88, 52.49025671027636)
(88, 52.49025671027636)
(73, 72.2

(95, 45.95814902250696)
(95, 45.95814902250696)
(95, 42.60420633707102)
(95, 42.60420633707102)
(20, 45.30026930482513)
(20, 45.30026930482513)
(16, 41.806544469892884)
(16, 41.806544469892884)
(16, 40.37220122535021)
(16, 40.37220122535021)
(30, 40.0796065173798)
(18, 39.53553504516427)
(18, 39.53553504516427)
(32, 40.462372349095986)
(32, 40.462372349095986)
(32, 41.096544108467)
(32, 41.096544108467)
(32, 39.893299029182174)
(32, 39.893299029182174)
(32, 40.76496337567455)
(32, 40.76496337567455)
(18, 39.03309000958373)
(18, 39.59641647838881)
(18, 39.59641647838881)
(18, 39.71956397824468)
(18, 39.71956397824468)
(18, 39.6667663162694)
(18, 39.6667663162694)
(88, 40.49036222023811)
(88, 40.49036222023811)
(18, 38.865576239582275)
(18, 38.865576239582275)
(18, 37.978439346154794)
(18, 37.978439346154794)
(18, 38.70567169640922)
(18, 38.70567169640922)
(18, 38.52271407696374)
(18, 38.52271407696374)
(16, 37.421387821053834)
(16, 37.421387821053834)
(18, 38.941310689293026)
(18, 38.94

(97, 53.77206466253109)
(97, 53.77206466253109)
(97, 55.63047247689926)
(97, 55.63047247689926)
(97, 56.23352620863074)
(97, 56.23352620863074)
(97, 54.41788869346649)
(97, 54.41788869346649)
(97, 55.179923169818316)
(97, 55.179923169818316)
(97, 61.788005402767524)
(97, 61.788005402767524)
(97, 62.394111741425526)
(97, 62.394111741425526)
(97, 61.888137892836795)
(97, 61.888137892836795)
(97, 59.03548001107503)
(97, 59.03548001107503)
(97, 60.25332226762591)
(97, 60.25332226762591)
(97, 62.0531710018041)
(97, 62.0531710018041)
(97, 61.67800851143703)
(97, 61.67800851143703)
(97, 60.007889439516916)
(97, 60.007889439516916)
(97, 58.96338577910603)
(97, 58.96338577910603)
(97, 56.99617018340864)
(97, 56.99617018340864)
(97, 60.068921093046995)
(97, 60.068921093046995)
(97, 57.26669931107534)
(97, 57.26669931107534)
(97, 60.480637153734094)
(97, 60.480637153734094)
(97, 60.056339378333895)
(97, 60.056339378333895)
(97, 60.98619356379263)
(97, 60.98619356379263)
(0, 64.65907353111076)
(0,

(97, 60.59633865335417)
(97, 60.59633865335417)
(97, 61.00919943328536)
(97, 61.00919943328536)
(97, 60.25446426368482)
(97, 60.25446426368482)
(97, 58.665317606847594)
(97, 58.665317606847594)
(97, 56.58553847119451)
(97, 56.58553847119451)
(97, 54.689787010463334)
(97, 54.689787010463334)
(97, 62.78383908912324)
(97, 62.78383908912324)
(97, 56.85882106465781)
(97, 56.85882106465781)
(97, 49.860775066058864)
(97, 49.860775066058864)
(97, 45.19761540982211)
(97, 45.19761540982211)
(88, 43.21962186477168)
(88, 43.21962186477168)
(88, 40.45727056062484)
(88, 40.45727056062484)
(88, 41.2680343528623)
(88, 41.2680343528623)
(88, 44.08446827164351)
(88, 44.08446827164351)
(75, 48.37744631322065)
(75, 48.37744631322065)
(88, 47.77327653058746)
(88, 47.77327653058746)
(88, 50.50985117930996)
(88, 50.50985117930996)
(88, 52.7045379034001)
(88, 52.7045379034001)
(73, 49.53293981153782)
(73, 49.53293981153782)
(88, 40.27264067058966)
(88, 40.27264067058966)
(97, 44.7022010040631)
(97, 44.7022010

(97, 52.01742718721259)
(97, 52.01742718721259)
(97, 49.00501988901539)
(97, 49.00501988901539)
(97, 51.19228396974874)
(97, 51.19228396974874)
(97, 51.08362626669421)
(97, 51.08362626669421)
(95, 52.34058782474205)
(95, 52.34058782474205)
(95, 52.33317194576904)
(95, 52.33317194576904)
(14, 58.71716258038657)
(14, 58.71716258038657)
(4, 57.88708001228071)
(4, 57.88708001228071)
(95, 56.79216318136684)
(95, 56.79216318136684)
(97, 57.47478796294982)
(97, 57.47478796294982)
(97, 56.93502301167918)
(97, 56.93502301167918)
(95, 58.172825031963114)
(95, 58.172825031963114)
(93, 56.77218432150159)
(93, 56.77218432150159)
(93, 47.90631670907121)
(93, 47.90631670907121)
(93, 47.97712985225306)
(93, 47.97712985225306)
(93, 49.87036536924439)
(93, 49.87036536924439)
(93, 44.57694459861697)
(93, 44.57694459861697)
(93, 43.64113412711791)
(93, 43.64113412711791)
(93, 42.602268062945384)
(93, 42.602268062945384)
(93, 42.33064738417412)
(93, 42.33064738417412)
(93, 45.861502498065725)
(93, 43.12555

(53, 111.17539100186004)
(53, 111.17539100186004)
(97, 51.06850286828829)
(97, 51.06850286828829)
(97, 49.32791656239583)
(97, 49.32791656239583)
(73, 51.92163141043038)
(44, 106.68850704478152)
(44, 106.68850704478152)
(73, 50.92177342361114)
(73, 50.92177342361114)
(73, 48.96179325998063)
(73, 48.96179325998063)
(88, 46.43677039187313)
(88, 46.43677039187313)
(97, 48.55303482432944)
(97, 48.55303482432944)
(55, 112.1299461348391)
(55, 112.1299461348391)
(88, 45.64949525070927)
(88, 45.64949525070927)
(97, 46.21144856442806)
(97, 46.21144856442806)
(97, 45.201755843501175)
(97, 45.201755843501175)
(97, 44.997600244657264)
(97, 44.997600244657264)
(97, 46.41886908746117)
(97, 46.41886908746117)
(97, 44.88863427300764)
(97, 44.88863427300764)
(88, 45.6237233982204)
(88, 45.6237233982204)
(97, 43.63420675847468)
(97, 43.63420675847468)
(97, 44.6646115320239)
(97, 44.6646115320239)
(97, 43.31903123711776)
(97, 43.31903123711776)
(97, 46.1582301311517)
(97, 46.1582301311517)
(97, 44.453040

(75, 51.669152724461995)
(75, 51.669152724461995)
(75, 51.14857787021538)
(75, 51.14857787021538)
(88, 48.12400402670295)
(88, 48.12400402670295)
(88, 51.06615565696548)
(88, 51.06615565696548)
(49, 112.01772066479013)
(49, 112.01772066479013)
(88, 47.87803732376845)
(88, 47.87803732376845)
(88, 45.57023583522873)
(88, 45.57023583522873)
(75, 48.50492328266132)
(75, 48.50492328266132)
(88, 45.45865608691577)
(88, 45.45865608691577)
(88, 44.875787570686875)
(88, 44.875787570686875)
(88, 44.48218026836397)
(88, 44.48218026836397)
(88, 43.6976300423799)
(88, 43.6976300423799)
(71, 42.60057598282667)
(71, 42.60057598282667)
(75, 45.589738289403336)
(75, 45.589738289403336)
(88, 43.95851294720943)
(88, 40.54292127331815)
(88, 40.54292127331815)
(88, 39.52332498233194)
(88, 39.52332498233194)
(88, 38.350047106344796)
(88, 38.350047106344796)
(71, 40.33121142703836)
(71, 40.33121142703836)
(75, 41.22573489243902)
(75, 41.22573489243902)
(75, 40.88218054603431)
(75, 40.88218054603431)
(88, 40.

(84, 64.87647672830401)
(84, 64.87647672830401)
(47, 114.13193258210283)
(47, 114.13193258210283)
(49, 103.51912221385284)
(49, 103.51912221385284)
(49, 101.57987864020136)
(49, 101.57987864020136)
(49, 102.81340976923006)
(49, 102.81340976923006)
(49, 108.92385409655408)
(49, 108.92385409655408)
(55, 107.08440139543183)
(55, 107.08440139543183)
(49, 105.19268006757926)
(49, 105.19268006757926)
(47, 107.04819893965097)
(53, 108.55113255318018)
(53, 108.55113255318018)
(49, 107.9295422004233)
(49, 107.9295422004233)
(47, 102.12188813697429)
(47, 102.12188813697429)
(49, 106.03263184628351)
(49, 106.03263184628351)
(49, 101.36796565183575)
(49, 101.36796565183575)
(49, 106.67742127265487)
(47, 103.00196933600652)
(47, 103.00196933600652)
(38, 102.32067947688934)
(38, 102.32067947688934)
(49, 111.09243128131583)
(49, 111.09243128131583)
(49, 107.92503470873254)
(49, 107.92503470873254)
(49, 101.13693883152033)
(49, 101.13693883152033)
(38, 103.22828073612858)
(38, 103.22828073612858)
(53,

In [30]:
result[1]

34.6903959619379